In [7]:
print("hello I'm excited to learn PyTorch")

hello I'm excited to learn PyTorch


In [8]:
!nvidia-smi

Wed Jun 25 21:32:28 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Pytorch Fundamentals
Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [9]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensors

Tensors are created using torch.tensor()

In [10]:
## Scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [11]:
scalar.ndim

0

In [12]:
scalar.item()

7

In [13]:
## Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

In [16]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [17]:
MATRIX.ndim

2

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [22]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [23]:
TENSOR = torch.tensor([[[[1,2,3],
                        [3,6,9],
                        [2,4,5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [24]:
TENSOR.ndim

4

In [25]:
TENSOR = torch.tensor([[[[1,2,3,4],
                        [3,6,9,10],
                        [2,4,5,6]]]])
TENSOR

tensor([[[[ 1,  2,  3,  4],
          [ 3,  6,  9, 10],
          [ 2,  4,  5,  6]]]])

In [26]:
TENSOR.size

<function Tensor.size>

In [27]:
TENSOR.shape

torch.Size([1, 1, 3, 4])

In [28]:
TENSOR.ndim

4

# Random Tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random numbers, look at data, update random numbers, look at data, update random numbers'

In [29]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9497, 0.0687, 0.3962, 0.5779],
        [0.8420, 0.2939, 0.0016, 0.1672],
        [0.7556, 0.7364, 0.4284, 0.4591]])

In [30]:
# Create a random tensor with sililar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [31]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

# Create a tensor of all ones

In [33]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [35]:
torch.range(0,10)

/tmp/ipython-input-35-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=ones)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Tensor datatypes

In [38]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [39]:
float_32_tensor.dtype

torch.float32

### Tensor datatypes are one of the big 3 errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [40]:
float_32_tensor.dtype

torch.float32

In [41]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [43]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9240, 0.4293, 0.7974, 0.2443],
        [0.6113, 0.9972, 0.3476, 0.7149],
        [0.6747, 0.1741, 0.9003, 0.8445]])

In [44]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9240, 0.4293, 0.7974, 0.2443],
        [0.6113, 0.9972, 0.3476, 0.7149],
        [0.6747, 0.1741, 0.9003, 0.8445]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [45]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [46]:
# Multiply tensor by 10
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [47]:
tensor

tensor([10, 20, 30])

In [48]:
# Subract 10
tensor = tensor - 10
tensor

tensor([ 0, 10, 20])

In [49]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)


tensor([  0, 100, 200])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix Multiplication ("dot product")

There are 2 main rules tht oerforming matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* (3,2) @ (3,2) wont work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work
2. The resulting matrix has the shape of the **outer dimensions**:
* (2,3) @ (3,2) -> (2,2)

In [50]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.5477, 0.6060, 0.3162],
        [0.8002, 0.3731, 0.5226],
        [0.8896, 0.8290, 0.5320]])

In [51]:
# Element wise multiplication
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [52]:
tensor * tensor

tensor([1, 4, 9])

In [53]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [54]:
# Matmul by hand
1*1 + 2*2 + 3*3

14

Using PyTorch built-in functions are faster

In [55]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 518 µs, sys: 0 ns, total: 518 µs
Wall time: 736 µs


In [56]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 35 µs, sys: 0 ns, total: 35 µs
Wall time: 38.1 µs


tensor(14)

### One of the most common errors in deep learning are: Shape Errors

In [57]:
# Shapes for matmul
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm(tensor_A, tensor_B) #mm is the same as matmul

In [58]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues we can use transpose

A **transpose** switches the axes or dimensions of a given tensor.

In [59]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [60]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [61]:
# The matrix multiplication works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc.(tensor aggregation)

In [62]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [64]:
# Find the max
x.max()

tensor(90)

In [65]:
# Find the mean #torch.mean requires float32
torch.mean(x.type(torch.float32))

tensor(45.)

In [66]:
#Sum
torch.sum(x)

tensor(450)

In [67]:
# Finding the index of min
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [68]:
# Finding the index of max
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [69]:
x[1]

tensor(10)

## Reshaping, stacking, squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all '1'dimensions from a tensor
* Unsqueeze - Add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [70]:
# Create tensor
import torch

x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [71]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [73]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [74]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [76]:
# Torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [77]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [78]:
x_reshaped.shape

torch.Size([1, 9])

In [79]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [80]:
x_reshaped.squeeze().shape

torch.Size([9])

In [81]:
# Torch.permute - rearranges the dimensions of a target tensor in a specified order
# Often used with images
x_original = torch.rand(size=(224,224,3)) # height, width, color channels

# Permute (swap) the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # color_channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [82]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [83]:
# Create a tensor
import torch

x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [84]:
# Index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [85]:
# Index on middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [86]:
x[0][0][0] #Last dimension, 0th element

tensor(1)

In [87]:
# Try to find 9
x[0][2][2]

tensor(9)

In [88]:
# You can also use ':' to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [89]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [90]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [91]:
# Try to get 4 for from the tensor
x[0,1,0]

tensor(4)

In [92]:
# Get index of 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [93]:
# Try to find 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

In [94]:
x[:,1,0] # Can use semicolon to select all from a dimension

tensor([4])

## PyTorch Tensors & NumPy

NumPy is a popular scientific python numerical computing library.

Pytorch has functionality to interact with it.

* Data in numpy, want in pytorch tensor -> 'torch.from_numpy(ndarray)'
* Pytorch tensor -> Numpy -> torch.tensor.numpy()

In [95]:
# Numpy array to tensor

import torch
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array).type(torch.float32) # When converting from numpy to pytorch, pytorch reflects umpys default data type of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [96]:
tensor.dtype

torch.float32

In [97]:
torch.arange(1.0,8.0).dtype

torch.float32

In [98]:
# Change the value of array, what will this do to tensor? # It doesnt change tensor value
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [99]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [100]:
# Change the tensor, what happens to the numpy tensor? # numpy tensor remains the same, they dont share memory
tensor = tensor + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([2., 2., 2., 2., 2., 2., 2.]))

## Reproducability (terying to take the random out of random)

In short how a nn works:

'Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again, again, again

* To reduce randomness in nn and pytorch comes the concept of a **random seed**.

* Random seed "flavors" the randomness

In [101]:
torch.rand(3,3)


tensor([[0.3890, 0.4965, 0.4932],
        [0.1480, 0.0772, 0.0453],
        [0.4548, 0.2548, 0.7313]])

In [102]:
import torch
## Create 2 random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4593, 0.0021, 0.5487, 0.7446],
        [0.9867, 0.0656, 0.4318, 0.3742],
        [0.2004, 0.8831, 0.5564, 0.5962]])
tensor([[0.9782, 0.9929, 0.0728, 0.9483],
        [0.7847, 0.7513, 0.4920, 0.2683],
        [0.4074, 0.2300, 0.7495, 0.7237]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [103]:
# Let's make some random but reproducable tensors
import torch

# Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducability

* https://docs.pytorch.org/docs/stable/notes/randomness.html

## Running tensors and pytorch objects on the GPU's

### 1. Getting a GPU
1. Easiest - Use Colab for a free GPU (options to upgrade to colab pro)
2. Use your own GPU
3. Use cloud computing such as AWS, pay as you go




In [104]:

!nvidia-smi

Wed Jun 25 21:32:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [105]:
# Check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

In [106]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [107]:
# Count number of devices
torch.cuda.device_count()

1

### Best practice to setup device agnostic code

## 3. Putting tensors and models on the gpu

* We want models and tensors on gpu because it computes faster

In [108]:
# Create tensor
import torch
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [112]:
# Move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to CPU

In [115]:
# To fix the GPU tensor with numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [116]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')